name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository Code
        uses: actions/checkout@v3 

     
      - name: Set up JDK 17 Development Environment
        uses: actions/setup-java@v3 
        with:
          java-version: 17
        

    
      - name: Cache Maven Dependencies
        uses: actions/cache@v3 
        with:
          path: ~/.m2
       
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ github.repository }}-${{ github.ref_name }}
          restore-keys:
            - ${{ runner.os }}-m2-${{ github.repository }}-${{ github.ref_name }}
            - ${{ runner.os }}-m2-${{ github.repository }}
            - ${{ runner.os }}-m2

    
      - name: Run Project Tests with Maven
        run: mvn -B test
